### PR TITLE
Don't show reviewer in approval notification

### LINKED ISSUE #798: Notifications should not show who approved a plugin
**Describe the bug**
As part of the review process, reviewers should be anonymous. However, upon approval of a plugin, the notification shows the avatar of the person who marked it as safe - it should not.

I don't know if this is the case for plugins marked as requiring changes.

**To Reproduce**

* Upload a plugin
* Hope it gets approved
* Look at the notifications
* See that the notification says that the plugin was approved, and that the avatar is that of a reviewer's

**Expected behavior**
The notification should not have any way to identify who reviewed the plugin

**Screenshots**
I won't do this, as it reveals who has been reviewing Nucleus.

**Environment (please complete the following information):**
N/A

**Additional context**
I don't know if this happens on "requires changes", but I'd check that too.

### PR DESCRIPTION
**Pull request by felixoi**
Fixes #798

preview

### CODE REVIEW

File: ore/app/models/user/Notification.scala [hunk 1]
```diff
@@ -35,8 +35,13 @@ case class Notification(
     *
     * @return User from which this originated from
     */
-  def origin(implicit service: ModelService): IO[Model[User]] =
-    ModelView.now(User).get(this.originId).getOrElseF(IO.raiseError(new NoSuchElementException("Get on None")))
+  def origin(implicit service: ModelService): OptionT[IO, Model[User]] =
+    OptionT
+      .fromOption[IO](originId)
+      .semiflatMap(
```
Comment (Katrix) [inline ore/app/models/user/Notification.scala]: Curly braces here?

**Review by Katrix — APPROVED** [review]

**Review by Katrix — CHANGES_REQUESTED** [review]
Failed to go down with the evolution

**Review by Katrix — APPROVED** [review]
