### PR TITLE
Show Flags unread notification

### LINKED ISSUE #597: Flags item on menu does not show that there are active flags
* Browser: `Google Chrome`

* Operating System: `Windows 7`

* Page link: `https://ore.spongepowered.org/`

* Steps to reproduce:

    * Visit any page while there are unresolved flags.
    * Look at menu.

Reality on left, mspaint expectation on right.

image

### PR DESCRIPTION
**Pull request by Ewoutvans**
Fix #597

### CODE REVIEW

File: app/models/viewhelper/HeaderData.scala [hunk 1]
```diff
@@ -4,11 +4,12 @@ import controllers.sugar.Requests.ProjectRequest
 import db.ModelService
 import db.impl.OrePostgresDriver.api._
 import db.impl.access.OrganizationBase
-import db.impl.{ProjectTableMain, SessionTable, UserTable, VersionTable}
+import db.impl._
 import models.project.VisibilityTypes
 import models.user.User
 import ore.permission._
 import ore.permission.scope.GlobalScope
+import org.apache.commons.lang3.exception.ExceptionContext
```
Comment (Katrix) [inline app/models/viewhelper/HeaderData.scala]: Unused import

**Review by phase — APPROVED** [review]
