### PR TITLE
Fix last updated for new versions

### LINKED ISSUE #699: Ore main page not refreshed
* Browser: `Google Chrome, Microsoft Edge`

* Operating System: `Windows 10`

* Page link: `https://ore.spongepowered.org/`, `https://ore.spongepowered.org/?sort=4`

As I speak, 7 plugins have been updating on Ore in the last 24h and the Ore main page which should list plugins ordered by last update is not refreshed. I've tried on different browsers, on pc and on mobile.

### PR DESCRIPTION
**Pull request by felixoi**
Should fix #699

### CODE REVIEW

File: app/controllers/ApiController.scala [hunk 1]
```diff
@@ -1,15 +1,15 @@
 package controllers
 
-import java.util.{Base64, UUID}
+import java.sql.Timestamp
+import java.util.{Base64, UUID, Date}
+
 import javax.inject.Inject
 
 import scala.concurrent.{ExecutionContext, Future}
-
```
Comment (Katrix) [inline app/controllers/ApiController.scala]: Don't remove newlines in imports

File: app/controllers/ApiController.scala [hunk 2]
```diff
@@ -288,8 +287,14 @@ final class ApiController @Inject()(
                   case (newVersion, channel, tags) =>
                     val update =
                       if (formData.recommended)
-                        service.update(project.copy(recommendedVersionId = Some(newVersion.id.value)))
-                      else Future.unit
+                        service.update(
+                          project.copy(
+                            recommendedVersionId = Some(newVersion.id.value),
+                            lastUpdated = new Timestamp(new Date().getTime)
```
Comment (Katrix) [inline app/controllers/ApiController.scala:295]: Can you change the copyWith method to take the right time instead. This won't have any effect

**Review by Katrix — APPROVED** [review]
